#!/usr/bin/env bash

INPUT_DIR="./converted_md"
OUTPUT_BASE="./split_chapters"
mkdir -p "$OUTPUT_BASE"

for file in "$INPUT_DIR"/*.md; do
	filename=$(basename "$file" .md)
	arc_dir="${OUTPUT_BASE}/${filename}"
	mkdir -p "$arc_dir"

	echo "Splitting $filename..."

	csplit -f "$arc_dir/chapter_" -b "%03d.md" "$file" '/^Chapter [0-9]\+:/' '{*}' >/dev/null 2>&1

	i=1
	for f in "$arc_dir"/chapter_*.md; do
		newname=$(printf "chapter_%03d.md" "$i")
		mv "$f" "$arc_dir/$newname"
		i=$((i + 1))
	done
done
